param-space:
  environment:
    env_name:
      type: str
      choice: HalfCheetah-v4
    file-name:
      type: str
      choice: null
    render-graphics:
      type: bool
      choice: false
    horizon:
      type: int
      choice: 3000
  rollouts:
    num-workers:
      type: int
      choice: 4
    num-envs-per-worker:
      type: int
      choice: 2
    rollout_fragment_length:
      type: int
      choice: 64
  framework:
    type: str
    choice: torch
  training:
    lr:
      type: float
      choice: 0.0003
    lambda_:
      type: float
      choice: 0.95
    gamma:
      type: float
      choice: 0.99
    sgd_minibatch_size:
      type: int
      choice: 128
    train_batch_size:
      type: int
      choice: 512
    num_sgd_iter:
      type: int
      choice: 20
    use_gae:
      type: bool
      choice: true
    clip_param:
      type: float
      choice: 0.2
    model:
      type: dict
      choice: {
        "fcnet_hiddens": [256, 256],
        "use_lstm": true,
        }
  resources:
    num_gpus:
      type: int
      choice: 0
  evaluation:
    evaluation-interval:
      type: int
      choice: 4000
    evaluation-duration:
      type: int
      choice: 100


tuner-space:
  trainable:
    type: str
    choice: PPO
  ai-runtime-conditions:
    run-config:
      verbose:
        type: int
        choice: 1
    stop-config:
      training_iteration:
        type: int
        choice: 10000
      timesteps_total:
        type: int
        choice: 40000000
      episode_reward_mean:
        type: float
        choice: 1000.0
    checkpoint-config:
        checkpoint_frequency:
          type: int
          choice: 1000
        checkpoint_at_end:
          type: bool
          choice: true
